import { WidgetGroup } from '@utils/types';

export const FULL_RELAYS = [
  'wss://relay.damus.io',
  'wss://relay.primal.net',
  'wss://relayable.org',
  'wss://relay.nostr.band/all',
  'wss://nostr.mutinywallet.com',
];

export const FETCH_LIMIT = 20;

export const HASHTAGS = [
  { hashtag: '#food' },
  { hashtag: '#gaming' },
  { hashtag: '#nsfw' },
  { hashtag: '#bitcoin' },
  { hashtag: '#nostr' },
  { hashtag: '#nostrdesign' },
  { hashtag: '#security' },
  { hashtag: '#zap' },
  { hashtag: '#LFG' },
  { hashtag: '#zapchain' },
  { hashtag: '#shitcoin' },
  { hashtag: '#plebchain' },
  { hashtag: '#nodes' },
  { hashtag: '#hodl' },
  { hashtag: '#stacksats' },
  { hashtag: '#nokyc' },
  { hashtag: '#meme' },
  { hashtag: '#memes' },
  { hashtag: '#memestr' },
  { hashtag: '#nostriches' },
  { hashtag: '#dev' },
  { hashtag: '#anime' },
  { hashtag: '#waifu' },
  { hashtag: '#manga' },
  { hashtag: '#lume' },
  { hashtag: '#snort' },
  { hashtag: '#damus' },
  { hashtag: '#primal' },
];

export const WIDGET_KIND = {
  local: {
    network: 100,
    feeds: 101,
    files: 102,
    articles: 103,
    user: 104,
    thread: 105,
    follows: 106,
    notification: 107,
  },
  global: {
    feeds: 1000,
    files: 1001,
    articles: 1002,
    hashtag: 1003,
    topic: 108,
  },
  nostrBand: {
    trendingAccounts: 1,
    trendingNotes: 2,
  },
  other: {
    learnNostr: 90000,
  },
  tmp: {
    list: 10000,
    xfeed: 10001,
    xhashtag: 10002,
  },
};

export const TOPICS = [
  {
    title: 'Gaming',
    description: '',
    kind: WIDGET_KIND.global.topic,
    content: [
      '#gamestr',
      '#gaming',
      '#gamer',
      '#ps',
      '#playstation',
      '#videogames',
      '#game',
      '#xbox',
      '#games',
      '#twitch',
      '#fortnite',
      '#pc',
      '#memes',
      '#pcgaming',
      '#gamers',
      '#gamingcommunity',
      '#youtube',
      '#switch',
      '#gamergirl',
      '#nintendo',
      '#gta',
      '#callofduty',
      '#streamer',
      '#follow',
      '#pubg',
      '#videogame',
      '#esports',
      '#bhfyp',
      '#meme',
      '#twitchstreamer',
      '#art',
      '#genshinimpact',
      '#honkaiimpact',
      '#warthunder',
      '#hovoverse',
      '#arknights',
      '#soul',
      '#eldenring',
      '#steam',
      '#pubg',
      '#cs2',
      '#apexlegends',
      '#baldurgate3',
      '#starfield',
      '#gta6',
      '#gameoftheyear',
    ],
  },
  {
    title: 'Music',
    description: '',
    kind: WIDGET_KIND.global.topic,
    content: [
      '#audiostr',
      '#musicstr',
      '#music',
      '#love',
      '#hiphop',
      '#rap',
      '#art',
      '#musician',
      '#artist',
      '#musica',
      '#instagood',
      '#singer',
      '#dj',
      '#follow',
      '#rock',
      '#like',
      '#dance',
      '#guitar',
      '#s',
      '#photography',
      '#song',
      '#bhfyp',
      '#newmusic',
      '#producer',
      '#life',
      '#rapper',
      '#party',
      '#fashion',
      '#explorepage',
      '#viral',
      '#beats',
    ],
  },
  {
    title: 'Photography',
    description: '',
    kind: WIDGET_KIND.global.topic,
    content: [
      '#photography',
      '#photooftheday',
      '#love',
      '#photo',
      '#nature',
      '#picoftheday',
      '#like',
      '#photographer',
      '#beautiful',
      '#follow',
      '#art',
      '#fashion',
      '#travel',
      '#bhfyp',
      '#photoshoot',
      '#likeforlikes',
      '#instadaily',
      '#naturephotography',
      '#model',
      '#me',
      '#smile',
      '#style',
      '#instalike',
      '#happy',
      '#likes',
      '#myself',
      '#followme',
      '#followforfollowback',
    ],
  },
  {
    title: 'Art',
    description: '',
    kind: WIDGET_KIND.global.topic,
    content: [
      '#artstr',
      '#art',
      '#artist',
      '#love',
      '#drawing',
      '#photography',
      '#artwork',
      '#instagood',
      '#photooftheday',
      '#painting',
      '#fashion',
      '#like',
      '#artistsoninstagram',
      '#beautiful',
      '#illustration',
      '#digitalart',
      '#follow',
      '#design',
      '#nature',
      '#picoftheday',
      '#photo',
      '#bhfyp',
      '#sketch',
      '#style',
      '#arte',
      '#happy',
      '#cute',
      '#draw',
      '#artoftheday',
    ],
  },
  {
    title: 'Movie',
    description: '',
    kind: WIDGET_KIND.global.topic,
    content: [
      '#filmstr',
      '#moviestr',
      '#movies',
      '#movie',
      '#film',
      '#cinema',
      '#films',
      '#hollywood',
      '#actor',
      '#love',
      '#s',
      '#art',
      '#cinematography',
      '#actress',
      '#netflix',
      '#moviescenes',
      '#music',
      '#filmmaking',
      '#horror',
      '#instagood',
      '#bollywood',
      '#movienight',
      '#photography',
      '#comedy',
      '#cinephile',
      '#cine',
      '#tv',
      '#director',
      '#horrormovies',
      '#drama',
      '#filmmaker',
    ],
  },
  {
    title: 'Technology',
    description: '',
    kind: WIDGET_KIND.global.topic,
    content: [
      '#apple',
      '#xiaomi',
      '#huawei',
      '#ai',
      '#oppo',
      '#nostr',
      '#technology',
      '#tech',
      '#innovation',
      '#engineering',
      '#business',
      '#iphone',
      '#technews',
      '#science',
      '#design',
      '#gadgets',
      '#electronics',
      '#android',
      '#software',
      '#programming',
      '#smartphone',
      '#bhfyp',
      '#samsung',
      '#instagood',
      '#coding',
      '#computer',
      '#pro',
      '#education',
      '#security',
      '#gadget',
      '#mobile',
      '#technologynews',
    ],
  },
  {
    title: 'Anime',
    description: '',
    kind: WIDGET_KIND.global.topic,
    content: [
      '#animestr',
      '#anime',
      '#manga',
      '#ntr',
      '#otaku',
      '#animeart',
      '#animegirl',
      '#cosplay',
      '#kawaii',
      '#weeb',
      '#onepiece',
      '#demonslayer',
      '#animeworld',
      '#aot',
      '#hentai',
      '#fanart',
    ],
  },
];

export const DEFAULT_WIDGETS: Array<WidgetGroup> = [
  {
    title: 'Topics',
    data: TOPICS,
  },
  {
    title: 'Local',
    data: [
      {
        kind: WIDGET_KIND.tmp.xfeed,
        title: 'Group feeds',
        description: 'All posts from specific people you want to keep up with',
      },
      {
        kind: WIDGET_KIND.local.files,
        title: 'Files',
        description: 'All files shared by people you follow',
      },
      {
        kind: WIDGET_KIND.local.articles,
        title: 'Articles',
        description: 'All articles shared by people you follow',
      },
    ],
  },
  {
    title: 'Global',
    data: [
      {
        kind: WIDGET_KIND.tmp.xhashtag,
        title: 'Hashtag',
        description: 'All posts have a specific hashtag',
      },
      {
        kind: WIDGET_KIND.global.files,
        title: 'Files',
        description: 'All files shared by people in your current relay set',
      },
      {
        kind: WIDGET_KIND.global.articles,
        title: 'Articles',
        description: 'All articles shared by people in your current relay set',
      },
    ],
  },
  {
    title: 'nostr.band',
    data: [
      {
        kind: WIDGET_KIND.nostrBand.trendingAccounts,
        title: 'Accounts',
        description: 'Trending accounts from the last 24 hours',
      },
      {
        kind: WIDGET_KIND.nostrBand.trendingNotes,
        title: 'Notes',
        description: 'Trending notes from the last 24 hours',
      },
    ],
  },
  {
    title: 'Other',
    data: [
      {
        kind: WIDGET_KIND.local.notification,
        title: 'Notification',
        description: 'Everything happens around you',
      },
    ],
  },
];
