export const FULL_RELAYS = [
  'wss://relay.damus.io',
  'wss://relayable.org',
  'wss://relay.nostr.band/all',
  'wss://nostr.mutinywallet.com',
];

export const FETCH_LIMIT = 20;

export const HASHTAGS = [
  { hashtag: '#food' },
  { hashtag: '#gaming' },
  { hashtag: '#nsfw' },
  { hashtag: '#bitcoin' },
  { hashtag: '#nostr' },
  { hashtag: '#nostrdesign' },
  { hashtag: '#security' },
  { hashtag: '#zap' },
  { hashtag: '#LFG' },
  { hashtag: '#zapchain' },
  { hashtag: '#shitcoin' },
  { hashtag: '#plebchain' },
  { hashtag: '#nodes' },
  { hashtag: '#hodl' },
  { hashtag: '#stacksats' },
  { hashtag: '#nokyc' },
  { hashtag: '#meme' },
  { hashtag: '#memes' },
  { hashtag: '#memestr' },
  { hashtag: '#nostriches' },
  { hashtag: '#dev' },
  { hashtag: '#anime' },
  { hashtag: '#waifu' },
  { hashtag: '#manga' },
  { hashtag: '#lume' },
  { hashtag: '#snort' },
  { hashtag: '#damus' },
  { hashtag: '#primal' },
];

export const WIDGET_KIND = {
  user: 1,
  thread: 2,
  group: 3,
  article: 4,
  file: 5,
  trendingNotes: 6,
  trendingAccounts: 7,
  topic: 8,
  hashtag: 9,
  notification: 9998,
  newsfeed: 9999,
  list: 10000,
};

export const TOPICS = [
  {
    title: 'Gaming',
    content: [
      '#gamestr',
      '#gaming',
      '#gamer',
      '#ps',
      '#playstation',
      '#videogames',
      '#game',
      '#xbox',
      '#games',
      '#twitch',
      '#fortnite',
      '#pc',
      '#pcgaming',
      '#gamers',
      '#gamingcommunity',
      '#switch',
      '#gamergirl',
      '#nintendo',
      '#gta',
      '#callofduty',
      '#pubg',
      '#videogame',
      '#esports',
      '#genshinimpact',
      '#honkaiimpact',
      '#warthunder',
      '#hoyoverse',
      '#arknights',
      '#soullike',
      '#eldenring',
      '#steam',
      '#pubg',
      '#cs2',
      '#apexlegends',
      '#baldurgate3',
      '#starfield',
      '#gta6',
      '#gameoftheyear',
      '#darksoul',
      '#batterfield',
      '#dota',
      '#rpg',
      '#thewitcher',
      '#rogally',
      '#rog',
      '#indiegames',
      '#indiedev',
      '#gamedev',
    ],
  },
  {
    title: 'Music',
    content: [
      '#audiostr',
      '#musicstr',
      '#music',
      '#love',
      '#hiphop',
      '#rap',
      '#art',
      '#musician',
      '#artist',
      '#musica',
      '#singer',
      '#dj',
      '#rock',
      '#dance',
      '#guitar',
      '#song',
      '#newmusic',
      '#producer',
      '#life',
      '#rapper',
      '#party',
      '#fashion',
      '#explorepage',
      '#viral',
      '#beats',
      '#dvd',
      '#amass',
      '#bluray',
      '#Blu_Ray',
      '#taylor',
    ],
  },
  {
    title: 'Photography',
    content: [
      '#photography',
      '#photooftheday',
      '#love',
      '#photo',
      '#nature',
      '#picoftheday',
      '#photographer',
      '#beautiful',
      '#fashion',
      '#travel',
      '#photoshoot',
      '#naturephotography',
      '#model',
      '#me',
      '#smile',
      '#style',
      '#happy',
      '#likes',
      '#myself',
    ],
  },
  {
    title: 'Art',
    content: [
      '#nostrdesign',
      '#artstr',
      '#art',
      '#artist',
      '#drawing',
      '#artwork',
      '#painting',
      '#fashion',
      '#beautiful',
      '#illustration',
      '#digitalart',
      '#design',
      '#nature',
      '#photo',
      '#sketch',
      '#style',
      '#arte',
      '#happy',
      '#cute',
      '#draw',
      '#artoftheday',
    ],
  },
  {
    title: 'Movie',
    content: [
      '#filmstr',
      '#moviestr',
      '#movies',
      '#movie',
      '#film',
      '#cinema',
      '#films',
      '#hollywood',
      '#actor',
      '#cinematography',
      '#actress',
      '#netflix',
      '#moviescenes',
      '#music',
      '#filmmaking',
      '#horror',
      '#bollywood',
      '#movienight',
      '#photography',
      '#comedy',
      '#cinephile',
      '#cine',
      '#tv',
      '#director',
      '#horrormovies',
      '#drama',
      '#filmmaker',
    ],
  },
  {
    title: 'Technology',
    content: [
      '#apple',
      '#xiaomi',
      '#huawei',
      '#ai',
      '#oppo',
      '#nostr',
      '#technology',
      '#tech',
      '#innovation',
      '#engineering',
      '#business',
      '#iphone',
      '#technews',
      '#science',
      '#gadgets',
      '#electronics',
      '#android',
      '#software',
      '#programming',
      '#smartphone',
      '#samsung',
      '#coding',
      '#computer',
      '#security',
      '#gadget',
      '#mobile',
      '#technologynews',
      '#opensource',
      '#tor',
      '#bitcoin',
      '#lightning',
    ],
  },
  {
    title: 'Anime',
    content: [
      '#animestr',
      '#anime',
      '#manga',
      '#otaku',
      '#animeart',
      '#animegirl',
      '#cosplay',
      '#weeb',
      '#onepiece',
      '#demonslayer',
      '#animeworld',
      '#aot',
      '#fanart',
      '#vocaloid',
      '#vtuber',
      '#fate',
      '#hololive',
      '#hololivemeet',
      '#pixiv',
      '#waifu',
    ],
  },
  {
    title: 'NSFW',
    content: [
      '#pornstr',
      '#porn',
      '#nsfw',
      '#bdsm',
      '#lewd',
      '#kink',
      '#sexy',
      '#loli',
      '#hentai',
      '#ntr',
    ],
  },
];
