// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
  interface Window {
    __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
  }
}

const invoke = window.__TAURI_INVOKE__;

export function getAccount() {
  return invoke<Account[]>('get_account');
}

export function createAccount(data: CreateAccountData) {
  return invoke<Account>('create_account', { data });
}

export function createFollow(data: CreateFollowData) {
  return invoke<Follow>('create_follow', { data });
}

export type Account = { id: number; pubkey: string; privkey: string; active: boolean; metadata: string };
export type Follow = { id: number; pubkey: string; kind: number; metadata: string; accountId: number };
export type CreateFollowData = { pubkey: string; kind: number; metadata: string; account_id: number };
export type CreateAccountData = { pubkey: string; privkey: string; metadata: string };
